# Numpy Array vs List

In [194]:
import numpy as np
arr = np.array([1,2,3,4,5])

In [2]:
arr

array([1, 2, 3, 4, 5])

In [3]:
arr[0]

1

In [4]:
arr[1]

2

In [5]:
arr[0:4]

array([1, 2, 3, 4])

In [6]:
arr[-1]

5

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr.ndim

1

In [9]:
arr.shape

(5,)

In [10]:
arr2 = np.array([1,2,3,4,5,'hello','hi'])

In [11]:
arr2

array(['1', '2', '3', '4', '5', 'hello', 'hi'], dtype='<U21')

In [12]:
import sys
sys.getsizeof(list())

64

In [13]:
sys.getsizeof(np.array([]))

96

In [14]:
sys.getsizeof([1,2,3,4,5,6,7,8,9,10])

144

In [15]:
sys.getsizeof(np.array([1,2,3,4,5,6,7,8,9,10]))

176

In [16]:
list1 = [i for i in range(10000)]

In [17]:
sys.getsizeof(list1)

87624

In [18]:
sys.getsizeof(np.array(list1))

80096

# Ways to create array

In [19]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [20]:
np.array(range(1,101))

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [21]:
np.array([i for i in range(1,101) if i % 2 == 0])

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [22]:
np.arange(1,101,3)

array([  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
        40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
        79,  82,  85,  88,  91,  94,  97, 100])

In [23]:
np.linspace(1,100,num=20,endpoint=False,retstep=True)

(array([ 1.  ,  5.95, 10.9 , 15.85, 20.8 , 25.75, 30.7 , 35.65, 40.6 ,
        45.55, 50.5 , 55.45, 60.4 , 65.35, 70.3 , 75.25, 80.2 , 85.15,
        90.1 , 95.05]), 4.95)

In [24]:
np.random.random()

0.3675697851177927

In [25]:
np.random.random(10)

array([0.00792695, 0.48211498, 0.90444088, 0.39756478, 0.92970868,
       0.87148544, 0.30177149, 0.35173942, 0.13049065, 0.87150297])

In [26]:
np.random.rand()

0.2627420322051448

In [27]:
np.random.rand(10)

array([0.08221748, 0.42080685, 0.31291814, 0.99917071, 0.68180827,
       0.30038404, 0.93536622, 0.26564754, 0.44562323, 0.56974348])

In [49]:
np.random.randint(100,1000,10)

array([402, 912, 391, 304, 271, 810, 889, 479, 831, 577])

# Multi-dimensional array

In [195]:
ndarr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [196]:
ndarr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [197]:
ndarr.shape

(3, 4)

In [198]:
ndarr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [201]:
arr2 = np.array([1,2,3,4,5,6])

In [202]:
arr2.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
ndarr[0]

array([1, 2, 3, 4])

In [32]:
ndarr[1]

array([5, 6, 7, 8])

In [33]:
ndarr[-1]

array([ 9, 10, 11, 12])

In [34]:
ndarr.ndim

2

In [35]:
ndarr.shape

(3, 4)

In [36]:
ndarr[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [37]:
ndarr[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [38]:
ndarr[:,0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [53]:
np.random.random([10,10])

array([[3.75516911e-01, 5.80543946e-01, 8.74986111e-01, 4.06153654e-01,
        1.78683794e-01, 4.62940678e-02, 2.32908577e-01, 5.36481116e-02,
        8.21423554e-01, 7.33855435e-01],
       [2.41127932e-01, 5.87334516e-01, 8.49467401e-02, 6.44893840e-01,
        8.13234612e-01, 4.01495152e-01, 5.05451074e-01, 6.03547251e-01,
        7.85885986e-03, 9.12888746e-01],
       [9.61568131e-01, 6.76905887e-02, 3.68831504e-01, 8.82051056e-01,
        2.54685347e-01, 8.19424141e-01, 9.61196403e-01, 9.49724802e-01,
        4.87804155e-01, 4.60558192e-01],
       [9.77479191e-03, 2.98613339e-01, 8.66629544e-01, 4.97494860e-01,
        6.61209905e-01, 3.21274633e-04, 8.16204653e-01, 4.23140592e-01,
        1.83767270e-02, 8.30498488e-01],
       [6.36408074e-01, 7.15854681e-01, 8.41905721e-01, 3.36517024e-01,
        1.85006020e-01, 7.34773139e-01, 7.79625779e-01, 4.15457694e-01,
        6.45318626e-01, 1.56204372e-02],
       [8.80091649e-01, 2.78379933e-01, 6.04853858e-02, 8.80181296e-01,
   

In [56]:
np.random.rand(2,5,5)

array([[[0.90362542, 0.29162579, 0.40728932, 0.46936739, 0.05579166],
        [0.0209413 , 0.84917345, 0.8102441 , 0.30642898, 0.32412898],
        [0.83810403, 0.41596319, 0.99849743, 0.9660532 , 0.51462145],
        [0.1682918 , 0.10471739, 0.55069989, 0.92985885, 0.71534118],
        [0.42223794, 0.62480421, 0.80733646, 0.20944726, 0.92512061]],

       [[0.0309217 , 0.37271136, 0.74168845, 0.45710925, 0.20271909],
        [0.34409383, 0.39331888, 0.84148931, 0.56436287, 0.68438372],
        [0.72505044, 0.81660501, 0.2140243 , 0.85563139, 0.95894339],
        [0.91119683, 0.48544465, 0.59002542, 0.14351167, 0.22841446],
        [0.51933126, 0.37915494, 0.29144619, 0.32316777, 0.76627664]]])

In [58]:
a = np.random.randint(10,100,[2,10])

In [59]:
a

array([[16, 42, 34, 85, 65, 70, 25, 43, 98, 88],
       [72, 10, 34, 48, 65, 74, 73, 82, 42, 30]])

In [60]:
a.shape

(2, 10)

In [158]:
np.random.seed(5)

In [159]:
np.random.random()

0.22199317108973948

In [160]:
np.random.random()

0.8707323061773764

In [161]:
np.random.random()

0.20671915533942642

In [162]:
np.random.random(10)

array([0.91861091, 0.48841119, 0.61174386, 0.76590786, 0.51841799,
       0.2968005 , 0.18772123, 0.08074127, 0.7384403 , 0.44130922])

In [163]:
np.random.random([2,5])

array([[0.15830987, 0.87993703, 0.27408646, 0.41423502, 0.29607993],
       [0.62878791, 0.57983781, 0.5999292 , 0.26581912, 0.28468588]])

In [168]:
arr1 = np.random.random(1000)

In [169]:
arr1.min()

0.00038289436747096506

In [171]:
arr1.max()

0.9985157672628341

In [172]:
arr1.mean()

0.4977658108714996

In [173]:
arr1.argmin()

197

In [175]:
arr1[197]

0.00038289436747096506

In [174]:
arr1.argmax()

278

In [176]:
arr1[278]

0.9985157672628341

In [187]:
arr1.argsort()

array([197, 757,   3, 521, 477,  11, 680, 859, 441, 613, 451, 269, 735,
       225,  56, 592, 168, 408, 867, 416, 970, 541, 669, 282,  64, 396,
         1, 865, 276, 718, 561, 256,  19, 123, 489, 969, 543,  34, 427,
       726, 279, 881, 674, 565, 981, 648, 357, 852, 785, 375, 962, 259,
       733, 921,  37, 425, 610,  69, 686, 558, 372, 945, 111,  97, 815,
       170, 332, 101, 737, 837, 916, 919, 283, 596, 943, 892, 166, 693,
       653, 258, 511, 794, 452, 607, 505, 863, 402, 251, 522,  80,  92,
       546, 103, 211,  20, 679, 435, 423, 883, 673,  32, 754, 472, 788,
       304, 506, 936,  51, 285, 944, 845, 118, 719, 973,  58,  21,  48,
       379, 922, 927, 709, 890, 585, 940, 187, 761, 449, 347, 214, 950,
       438, 263, 532, 678, 598, 989, 147, 609, 149, 294, 245, 880, 895,
       996, 192, 793, 821, 631, 861, 848, 830, 990, 195, 586, 584, 641,
       816, 503, 493, 422, 176, 199, 823, 736, 803, 888, 559, 405, 169,
       398, 182, 105, 937, 804, 336, 731, 564, 525, 721, 637, 24

In [177]:
arr2 = np.random.random([10,10])

In [178]:
arr2.argmin()

53

In [185]:
arr2[5][3]

0.010188654525792318

In [186]:
arr2.min()

0.010188654525792318

In [189]:
arr3 = np.array([[13,34,42,32], [34,43,76,23]])

In [ ]:
arr3.sort()

In [192]:
arr3

array([[13, 32, 34, 42],
       [23, 34, 43, 76]])

# Pandas Intro

In [134]:
dict1 = {
    'a' : ['Pant', 'Dhoni', 'Kohli', 'Rohit', 'Hardik', 'Bumrah', 'Chahal'],
    'b' : [30, 50, 70, 100, 50, None, None],
    'c' : [23.3, 49, 52, 54, 40, None, None]
}

In [98]:
import pandas as pd

In [135]:
df = pd.DataFrame(dict1)

In [136]:
#2d - dataframe - set of series
df

a      b     c
0    Pant   30.0  23.3
1   Dhoni   50.0  49.0
2   Kohli   70.0  52.0
3   Rohit  100.0  54.0
4  Hardik   50.0  40.0
5  Bumrah    NaN   NaN
6  Chahal    NaN   NaN

In [76]:
#1D - series
#df[['names']]
#pd.DataFrame(df['names'])
df[['names', 'average']]

names  average
0    Pant     23.3
1   Dhoni     49.0
2   Kohli     52.0
3   Rohit     54.0
4  Hardik     40.0
5  Bumrah      NaN
6  Chahal      NaN

In [78]:
df[0:4]

names  scores  average
0   Pant    30.0     23.3
1  Dhoni    50.0     49.0
2  Kohli    70.0     52.0
3  Rohit   100.0     54.0

In [80]:
df[0:1]

names  scores  average
0  Pant    30.0     23.3

In [90]:
df[df['names'] == 'Pant']

names  scores  average
0  Pant    30.0     23.3

In [93]:
df

names  scores  average
0    Pant    30.0     23.3
1   Dhoni    50.0     49.0
2   Kohli    70.0     52.0
3   Rohit   100.0     54.0
4  Hardik    50.0     40.0
5  Bumrah     NaN      NaN
6  Chahal     NaN      NaN

In [95]:
df.head(4)

names  scores  average
0   Pant    30.0     23.3
1  Dhoni    50.0     49.0
2  Kohli    70.0     52.0
3  Rohit   100.0     54.0

In [96]:
df.tail(2)

names  scores  average
5  Bumrah     NaN      NaN
6  Chahal     NaN      NaN

In [100]:
df

a      b     c
0    Pant   30.0  23.3
1   Dhoni   50.0  49.0
2   Kohli   70.0  52.0
3   Rohit  100.0  54.0
4  Hardik   50.0  40.0
5  Bumrah    NaN   NaN
6  Chahal    NaN   NaN

In [112]:
df = pd.DataFrame(dict1)

Names  Scores  Average
Batsman        Pant    30.0     23.3
Batsman       Dhoni    50.0     49.0
Batsman       Kohli    70.0     52.0
Batsman       Rohit   100.0     54.0
All-rounder  Hardik    50.0     40.0
Bowler       Bumrah     NaN      NaN
Bowler       Chahal     NaN      NaN

c       a      b
Batsman      23.3    Pant   30.0
Batsman      49.0   Dhoni   50.0
Batsman      52.0   Kohli   70.0
Batsman      54.0   Rohit  100.0
All-rounder  40.0  Hardik   50.0
Bowler        NaN  Bumrah    NaN
Bowler        NaN  Chahal    NaN

In [ ]:
df.columns = ['Names', 'Scores', 'Average']
df.index = ['Batsman', 'Batsman', 'Batsman', 'Batsman', 'All-rounder', 'Bowler', 'Bowler']
df

In [ ]:
columns = ['c', 'a', 'b']
rows = ['Batsman', 'Batsman', 'Batsman', 'Batsman', 'All-rounder', 'Bowler', 'Bowler']
pd.DataFrame(dict1, index = rows, columns=columns)

In [127]:
list1 = [['Pant', 'Dhoni', 'Kohli', 'Rohit', 'Hardik', 'Bumrah', 'Chahal'],
        [30, 50, 70, 100, 50, None, None],
        [23.3, 49, 52, 54, 40, None, None]]

In [128]:
list1

[['Pant', 'Dhoni', 'Kohli', 'Rohit', 'Hardik', 'Bumrah', 'Chahal'],
 [30, 50, 70, 100, 50, None, None],
 [23.3, 49, 52, 54, 40, None, None]]

In [129]:
arr1 = np.array(list1)

In [137]:
arr1
pd.DataFrame(arr1)

0      1      2      3       4       5       6
0  Pant  Dhoni  Kohli  Rohit  Hardik  Bumrah  Chahal
1    30     50     70    100      50    None    None
2  23.3     49     52     54      40    None    None

In [131]:
rows = ['names', 'scores', 'average']
columns = ['Batsman', 'Batsman', 'Batsman', 'Batsman', 'All-rounder', 'Bowler', 'Bowler']
df = pd.DataFrame(arr1, index=rows, columns = columns)

In [132]:
df.transpose()

names scores average
Batsman        Pant     30    23.3
Batsman       Dhoni     50      49
Batsman       Kohli     70      52
Batsman       Rohit    100      54
All-rounder  Hardik     50      40
Bowler       Bumrah   None    None
Bowler       Chahal   None    None

In [133]:
df

Batsman Batsman Batsman Batsman All-rounder  Bowler  Bowler
names      Pant   Dhoni   Kohli   Rohit      Hardik  Bumrah  Chahal
scores       30      50      70     100          50    None    None
average    23.3      49      52      54          40    None    None

In [138]:
df

a      b     c
0    Pant   30.0  23.3
1   Dhoni   50.0  49.0
2   Kohli   70.0  52.0
3   Rohit  100.0  54.0
4  Hardik   50.0  40.0
5  Bumrah    NaN   NaN
6  Chahal    NaN   NaN

In [142]:
df.isna()

a      b      c
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False   True   True
6  False   True   True

In [141]:
df.dropna()

a      b     c
0    Pant   30.0  23.3
1   Dhoni   50.0  49.0
2   Kohli   70.0  52.0
3   Rohit  100.0  54.0
4  Hardik   50.0  40.0

In [193]:
df.describe()

b          c
count    5.000000   5.000000
mean    60.000000  43.660000
std     26.457513  12.578871
min     30.000000  23.300000
25%     50.000000  40.000000
50%     50.000000  49.000000
75%     70.000000  52.000000
max    100.000000  54.000000

In [218]:
list1 = []

In [219]:
list2 = [1,2,3,4,5]

In [226]:
list1.append(list2)

In [229]:
np.array(list1)

array([list([1, 2, 3, 4, 5]), list([1, 2, 3, 4, 5]),
       list([1, 2, 3, 4, 5]), list([1, 2, 3, 4, 5]), list([])],
      dtype=object)

In [228]:
list1.append([])

In [214]:
np.array(list1)

array([list([1, 2, 3, 4, 5]), list([1, 2, 3, 4, 5]),
       list([1, 2, 3, 4, 5]), list([1, 2, 3, 4, 5]), list([])],
      dtype=object)