In [45]:
from sklearn.linear_model import LinearRegression 
import pandas as pd
import numpy as np

In [5]:
linReg = LinearRegression()

In [95]:
dataset = pd.read_csv('SaratogaHouses.csv')

In [96]:
x = dataset['livingArea'].values
#x.shape[0]

In [97]:
#x.reshape(len(x),1)
#x.reshape(x.shape[0],1)
x = x.reshape(-1,1)

In [98]:
y = dataset['price'].values

In [99]:
linReg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [100]:
linReg.predict([[906]])

array([115928.4169181])

In [101]:
y[0]

132500

In [102]:
y_pred = linReg.predict(x)

In [103]:
y_pred[:10]

array([115928.4169181 , 234367.71823171, 233349.61535509, 233349.61535509,
       108462.32915621, 143756.56221241, 324752.62916731, 201449.05855429,
       198055.38229888, 173620.91325997])

In [104]:
from sklearn.metrics import mean_squared_error

In [105]:
mse = mean_squared_error(y_pred, y)

In [106]:
rmse = np.sqrt(mse)

In [107]:
mse, rmse

(4769912967.014986, 69064.55651790567)

In [108]:
from sklearn.model_selection import train_test_split

In [109]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.20)

In [110]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1382, 1)
(346, 1)
(1382,)
(346,)


In [111]:
x_train[:5]

array([[1897],
       [1863],
       [1806],
       [2016],
       [1608]])

In [112]:
x_test[:5]

array([[ 912],
       [1404],
       [ 912],
       [ 824],
       [1561]])

In [113]:
reg2 = LinearRegression()

In [114]:
reg2.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [115]:
y_pred = reg2.predict(x_test)

In [116]:
mse = mean_squared_error(y_pred, y_test)

In [117]:
rmse = np.sqrt(mse)

In [118]:
mse, rmse

(5651773693.748605, 75178.27940135771)

In [119]:
#feature scaling - standardization
#we can use normalization also
from sklearn.preprocessing import StandardScaler

In [120]:
std = StandardScaler()

In [121]:
x = std.fit_transform(x)

In [122]:
x.min()

-1.837780390181007

In [123]:
x.max()

5.603856161728951

In [124]:
len(x)

1728

In [126]:
y = y.reshape(-1,1)

In [127]:
y = std.fit_transform(y)

In [128]:
y.min()

-2.103044415654399

In [129]:
y.max()

5.721132891573342

In [130]:
reg3 = LinearRegression()

In [131]:
reg3.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [132]:
y_pred = reg3.predict(x)

In [134]:
mse = mean_squared_error(y_pred,y)

In [135]:
rmse = np.sqrt(mse)

In [136]:
mse,rmse

(0.49250015531807584, 0.7017835530404484)

In [137]:
dataset.head()

Unnamed: 0   price  lotSize  age  landValue  livingArea  pctCollege  \
0           1  132500     0.09   42      50000         906          35   
1           2  181115     0.92    0      22300        1953          51   
2           3  109000     0.19  133       7300        1944          51   
3           4  155000     0.41   13      18700        1944          51   
4           5   86060     0.11    0      15000         840          51   

   bedrooms  fireplaces  bathrooms  rooms          heating      fuel  \
0         2           1        1.0      5         electric  electric   
1         3           0        2.5      6  hot water/steam       gas   
2         4           1        1.0      8  hot water/steam       gas   
3         3           1        1.5      5          hot air       gas   
4         2           0        1.0      3          hot air       gas   

               sewer waterfront newConstruction centralAir  
0             septic         No              No         No  
1             septic         No              No         No  
2  public/commercial         No              No         No  
3             septic         No              No         No  
4  public/commercial         No             Yes        Yes

In [138]:
z = dataset['centralAir'].values

In [139]:
pd.unique(dataset['centralAir'])

array(['No', 'Yes'], dtype=object)

In [140]:
z[:10]

array(['No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No'],
      dtype=object)

In [141]:
from sklearn.preprocessing import LabelEncoder

In [142]:
encoder = LabelEncoder()

In [145]:
z = encoder.fit_transform(z)

In [147]:
z[:10]

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])